onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - core-js
  - cos-js-sdk-v5
  - es5-ext
  - esbuild
  - typeit
  - vue-demi

allowedDeprecatedVersions:
  are-we-there-yet: "*"
  sourcemap-codec: "*"
  lodash.isequal: "*"
  domexception: "*"
  w3c-hr-time: "*"
  inflight: "*"
  npmlog: "*"
  rimraf: "*"
  stable: "*"
  gauge: "*"
  abab: "*"
  glob: "*"
