name: Build and Deploy
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

on:
  push:
    branches:
      - pages

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.com/

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Build static site
        run: |
          pnpm install --no-frozen-lockfile
          sed -i "s#VITE_PUBLIC_PATH = /#VITE_PUBLIC_PATH = /vue-pure-admin/#g" $(pwd)/.env.production
          pnpm build
          cd dist
          touch README.md .nojekyll

      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          clean: true
